---
#
# This will be expected to run as root.
# The initdb task will fail if a DB already exists.
- hosts: all
  tasks:
    - name: Install Postgresql Server
      yum:
        name: postgresql-server
        state: present
    - name: Install Postgres Contrib
      yum:
          name: postgresql-contrib
          state: present
    - name: Start Postgres DB Engine
      systemd: 
        name: postgresql
        enabled: yes
        state: started
    - name: Initialize DB
      command: "initdb"
      become: true
      become_method: su
      become_user: postgres
      become_flags: '-l'


